function output_txt = data_cursor(~,event_obj)

    hAxes = get(get(event_obj,'Target'),'Parent');
    assetData = getappdata(hAxes,'AssetData');
    I = get(event_obj, 'DataIndex');
    output_txt = {['Re: ',num2str(assetData.Re(I))],...
                  ['Im: ',num2str(assetData.Im(I))],...
                  ['Modul: ',num2str(assetData.Modul(I))],...
                  ['Faza: ',num2str(assetData.Faza(I))],...
                  ['Omega: ', num2str(assetData.Omega(I))]};
end